name: Python application

on:
  push:
    branches: [ "dev/faizan/endpoints/webservice-prototype" ]
  pull_request:
    branches: [ "dev/faizan/endpoints/webservice-prototype" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    # Setting PYTHONPATH to include the workspace
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check current directory
        run: |
          pwd
          ls -al

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
